services:
  frontend:
    image: jjoonleo/kubc-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
