services:
  frontend:
    image: jjoonleo/kubc-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
