services:
  frontend:
    image: jjoonleo/kubc-frontend
    container_name: frontend
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
